### ISSUE TITLE
NFT 데이터 적용 및 관리 방식 정리

### ISSUE THREAD

**Issue by doevery-1992** [codestates/BEB-05-KAL2#38]

**Comment by jihoon1** [comment]
![Image](https://user-images.githubusercontent.com/20811812/183616067-22aa7f03-c391-4996-9d92-ac68a11a04a3.png)

**Comment by jihoon1** [comment]
pinata.cloud 로 IPFS 저장소로 사용. 
사용에 필요한 API keys : API Key: - env 파일로 제공 예정. 

API 사용 가이드
	공식 홈페이지 API . https://docs.pinata.cloud/pinata-api/pinning/pin-file-or-directory

참고자료
        IPFS를 사용해야 하는 이유 https://medium.com/scrappy-squirrels/tutorial-nft-metadata-ipfs-and-pinata-9ab1948669a3

**Comment by jihoon1** [comment]
Firebase  DB - 프로토타입 작성시 가볍게 사용 가능한 DB 
                        NFT 마켓을 이용하는 유저 및 유저 보유 NFT 정보 저장 용도
         DB접근 config Data는 테스트 완료후 env 파일로 제공 예정.

홈페이지 API 설명 https://firebase.google.com/docs/reference/js?hl=ko
참고 블로그 https://velog.io/@dev-hannahk/react-firebase-crud



![Image](https://user-images.githubusercontent.com/20811812/183625056-5291f6d9-6ede-4cbd-9b52-3f5300accc2a.png)

**Comment by jihoon1** [comment]
완료
